In [1]:
import pandas as pd

In [18]:
file = "../corpora/raw/modified_file_updated_1.xlsx"
data = pd.read_excel(file, sheet_name=None)

In [19]:
data['command_1'].keys()

Index(['Metaphor/Similie', 'Unnamed: 1', 'Unnamed: 2'], dtype='object')

In [20]:
for command in data.keys():
    tactic_name = data[command].keys()[0]
    data[command] = data[command].rename(columns={tactic_name:'Index', 'Unnamed: 1':'sentence', 'Unnamed: 2':tactic_name})
    data[command] = data[command].drop(columns='Index')

In [21]:
data['command_1']

                                               sentence  Metaphor/Similie
0     Just as a conductor leads an orchestra, each s...               1.0
1     The figure of speech we find in these speeches...               1.0
2     Like an artist with a palette of colors, each ...               1.0
3     The figure of speech used by these individuals...               1.0
4     Just as a conductor leads an orchestra, each s...               1.0
...                                                 ...               ...
2765  As the next speaker stepped onto the stage, th...               1.0
2766  The room was like a playground of similes, as ...               1.0
2767  Each presenter approached similes with their o...               1.0
2768  Like a bouquet of flowers, the speakers' simil...               1.0
2769  The room was an alchemist's laboratory, as the...               1.0

[2770 rows x 2 columns]

In [31]:
df_list = list(data.values())
data_merged = pd.concat(df_list, ignore_index=True)

In [32]:
data_merged.fillna(0)

,sentence,Metaphor/Similie,Rhetorical question,Story/Anecdote,Contrast,Lists/Repetitions,Sentiment of the Collective,Moral Conviction,Ambitious goals,Confidence in goals
0,"Just as a conductor leads an orchestra, each s...",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,The figure of speech we find in these speeches...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"Like an artist with a palette of colors, each ...",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,The figure of speech used by these individuals...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"Just as a conductor leads an orchestra, each s...",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
95073,"""Our shared belief in our potential will be th...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
95074,"""Let us march forward fearlessly, knowing that...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
95075,"""Our collective determination to succeed will ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
95076,"""Together, we will transform our goals into re...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
95077,"""I firmly believe that our shared vision holds...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [33]:
data_merged.to_csv('../corpora/all_generated_tactics.csv')